sudo: required
services:
    - docker

before_install:
    - docker build -t tanekim77/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run tanekim77/react-test npm test -- --coverage

after_success:
    - docker build -t tanekim77/multi-client ./client
    - docker build -t tanekim77/multi-nginx ./nginx
    - docker build -t tanekim77/multi-server ./server
    - docker build -t tanekim77/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tanekim77/multi-client
    - docker push tanekim77/multi-nginx
    - docker push tanekim77/multi-server
    - docker push tanekim77/multi-worker